services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_DATABASE: students_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./university-groups-backend
    container_name: university-groups-backend
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: students_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - db

  frontend:
    build:
      context: ./university-groups-frontend
    container_name: university-groups-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data: